### ISSUE TITLE
add www_ambassadors

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/websites#4]
https://github.com/threefoldfoundation/www_conscious_internet (is the new name for hamdy conscious internet project)
https://github.com/threefoldfoundation/www_ambassadors (a copy of the project)
https://github.com/threefoldfoundation/data_threefold_projects_friends is the new name for the data repo that used to be (www_threefold_ecosystem)

@Pishoy can u please update the code to handle these changes and the www_ambassadors project too?

**Comment by Pishoy** [comment]
www_ambassador has been added
Also install.sh and start.sh scripts has been updated with new naming
